require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.1
  TargeRailsVersion: 7.0
  NewCops: enable
  Exclude:
  - 'bin/**/*'
  - 'vendor/**/*'
  - 'db/**/*'

Documentation:
  Enabled: false

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']

RSpec/ExampleLength:
  Max: 40

RSpec/MultipleExpectations:
  Enabled: false

RSpec/FilePath:
  Enabled: false

RSpec/ContextWording:
  Enabled: false
