require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.1
  Exclude:
  - 'bin/**/*'
  - 'vendor/**/*'
  - 'db/**/*'
  - 'config/**/*'
  - 'script/**/*'
  - 'spec/rails_helper.rb'

Documentation:
  Enabled: false

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context', 'feature', 'scenario', 'let']

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/FilePath:
  Enabled: false

RSpec/ContextWording:
  Enabled: false
