require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable
  Exclude:
  - bin/**/*
  - vendor/**/*
  - db/**/*

Style/Documentation:
  Enabled: false
Style/HashSyntax:
  Enabled: false

Layout/LineLength:
  Exclude:
    - config/initializers/devise.rb

RSpec/ExampleLength:
  Max: 40
RSpec/MultipleExpectations:
  Enabled: false
RSpec/ContextWording:
  Enabled: false
